### ISSUE TITLE
VdebugEval error "required argument [l:length] missing"

### ISSUE THREAD

**Issue by tygeng** [vim-vdebug/vdebug#157]
Hi, this plugin is amazing. However, I encountered this error when I try to issue :VdebugEval.

I am a Linux (XUbuntu 13.04) user and I am using Python 2.7.4 with vim 7.3.1314. I followed the help doc and used Komodo-PythonRemote 8.5.3 for linux x86-64. 

Whenever I try to evaluate some variables/expressions with F12 or <leader>e or :VdebugEval <the code>, I get this error in the debug log window: 
    - [ERROR] {Fri 25 2014 16:53:39} required argument [l:length] missing

Any ideas? Thanks!

**Comment by drewverlee** [comment]
Same problem as above.

Steps to reproduce:

1. install plugin using vundle
2. download and extract Komodo-PythonRemoteDebugging-8.5.4-86985-linux-x86_64.tar.gz
3. mv dbgp dir to where pydbgp exec file
4. download patchs from https://gist.github.com/3348076
5. apply patch (output below)

➜  854 git:(master) ✗ patch dbgp/client.py < client-8.5.0.patch
patching file dbgp/client.py
patch: **** '---' expected at line 8 of patch

6. form inside Gvim run :VdebugStart
7. from commnadline run: python -S path/to/pydbgp -d localhost:9000 myscript.py
8. debug session starts
9. set a break point
10. run
11.. VdebugEval -> complains about length.

**Comment by doronbehar** [comment]
I think the patch is outdated for the latest version.

I've installed the version available in pip ([packaged / maintained](https://github.com/agroszer/komodo-python3-dbgp) thanks to @agroszer) and then manually edited `client.py` according to the original patch and the problem was fixed.

Maybe @agroszer would be willing to patch it in his version, as part of the packaging process of every release? Or maybe we should nag upstream about this issue? Although we are not using their IDEs? What do you guys think?
